FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
ENV NEXT_PUBLIC_MICROSOFT_CLIENT_ID=651d3657-6c2d-4912-96ee-671000eac3fa
ENV NEXT_PUBLIC_MICROSOFT_AUTH_URL=https://login.microsoftonline.com/common/oauth2/v2.0/authorize?
ENV NEXT_PUBLIC_MICROSOFT_TENANT_ID=0cb9b4fd-5d18-4112-9dee-ec19b0bb72f8
ENV NEXT_PUBLIC_MICROSOFT_CLIENT_SECRET=ZMR8Q~Zr3f~dV~o03Z3gVIwwpEDqBZ~aTQK~ybTS
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built app
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]