version: "3.8"

services:
  chat-frontend:
    build:
      context: ./ai-chat
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=<>
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=<>
      - NEXT_PUBLIC_MICROSOFT_CLIENT_ID=<>
      - NEXT_PUBLIC_MICROSOFT_AUTH_URL=<>
      - NEXT_PUBLIC_MICROSOFT_TENANT_ID=<>
      - NEXT_PUBLIC_MICROSOFT_CLIENT_SECRET=<>
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=AI Data Agent
      - API_V1_STR=/api/v1
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ai_data_agent
      - SECRET_KEY=<>
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
      - QDRANT_URL=http://qdrant:6333
      - DEBUG=True
      - ENV=development
      - HF_HOME=/shared/huggingface_cache
      - ONEDRIVE_CLIENT_ID=<>
      - ONEDRIVE_CLIENT_SECRET=<>
      - MICROSOFT_TENANT_ID=<>
      - ONEDRIVE_REDIRECT_URI=http://localhost:3000/auth/callback/onedrive
      - OPENAI_API_KEY=<>
    volumes:
      - ./data:/app/data
      - ./shared_huggingface_cache:/shared/huggingface_cache
    depends_on:
      - mongodb
      - qdrant

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
  qdrant_data:
