version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=AI Data Agent
      - API_V1_STR=/api/v1
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ai_data_agent
      - SECRET_KEY=bc708dbcccb913f4d068fb526e2a922a444f32c99d7c5732cc15cb7f4365101d
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
      - QDRANT_URL=http://qdrant:6333
      - DEBUG=True
      - ENV=development
      - HF_HOME=/shared/huggingface_cache
      - ONEDRIVE_CLIENT_ID=651d3657-6c2d-4912-96ee-671000eac3fa
      - ONEDRIVE_CLIENT_SECRET=ZMR8Q~Zr3f~dV~o03Z3gVIwwpEDqBZ~aTQK~ybTS
      - MICROSOFT_TENANT_ID=0cb9b4fd-5d18-4112-9dee-ec19b0bb72f8
      - ONEDRIVE_REDIRECT_URI=http://localhost:3000/auth/callback/onedrive
    volumes:
      - ./data:/app/data
      - ./shared_huggingface_cache:/shared/huggingface_cache
    depends_on:
      - mongodb
      - qdrant

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
  qdrant_data:
