name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west10

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        token_format: access_token
        audience: https://iam.googleapis.com/projects/101349614136
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker auth
      run: |
        gcloud auth configure-docker europe-west10-docker.pkg.dev --quiet
    
    # - name: Build and push Chat Frontend Docker image
    #   run: |
    #     docker build --build-arg VITE_API_URL=/dataagent/api/v1 ./ai-chat -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/chat-frontend:latest -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/chat-frontend:${{ github.sha }}
    #     docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/chat-frontend:latest
    #     docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/chat-frontend:${{ github.sha }}
    
    # - name: Build and push Frontend Docker image
    #   run: |
    #     docker build ./frontend -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/frontend:latest -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/frontend:${{ github.sha }}
    #     docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/frontend:latest
    #     docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/frontend:${{ github.sha }}
    
    - name: Build and push Backend Docker image
      run: |
        docker build ./backend -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/backend:latest -t europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/backend:${{ github.sha }}
        docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/backend:latest
        docker push europe-west10-docker.pkg.dev/$PROJECT_ID/datanalysisagent/backend:${{ github.sha }}
