name: Build and Push to GCR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        token_format: access_token
        audience: https://iam.googleapis.com/projects/101349614136 

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'docker-credential-gcr'

    - name: Configure Docker auth
      run: |
        gcloud auth configure-docker gcr.io --quiet

    - name: Build and push Frontend Docker image
      run: |
        docker build ./frontend -t gcr.io/$PROJECT_ID/frontend:latest -t gcr.io/$PROJECT_ID/frontend:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/frontend:latest
        docker push gcr.io/$PROJECT_ID/frontend:${{ github.sha }}

    - name: Build and push Backend Docker image
      run: |
        docker build ./backend -t gcr.io/$PROJECT_ID/backend:latest -t gcr.io/$PROJECT_ID/backend:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/backend:latest
        docker push gcr.io/$PROJECT_ID/backend:${{ github.sha }}
        